# Generated by Django 3.1.3 on 2021-02-06 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('stack', models.CharField(max_length=200)),
                ('markdown_content', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('git', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('image', models.ImageField(default=None, null=True, upload_to='')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
