# Generated by Django 3.1.3 on 2021-01-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(default='project', max_length=30),
            preserve_default=False,
        ),
    ]
