# Generated by Django 3.1.3 on 2021-02-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_item_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='git',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
